2024-03-22 10:17:12,889 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-22 10:17:12,889 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Configure stats pid to 109749
2024-03-22 10:17:12,890 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Loading settings from /home/souvik/.config/wandb/settings
2024-03-22 10:17:12,890 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Loading settings from /mnt/d/WSL/Flight-Fare-Prediction/wandb/settings
2024-03-22 10:17:12,890 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-22 10:17:12,891 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-22 10:17:12,891 INFO    MainThread:109749 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240322_101712-aik2g0sd/logs/debug.log
2024-03-22 10:17:12,892 INFO    MainThread:109749 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240322_101712-aik2g0sd/logs/debug-internal.log
2024-03-22 10:17:12,892 INFO    MainThread:109749 [wandb_init.py:init():566] calling init triggers
2024-03-22 10:17:12,893 INFO    MainThread:109749 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-22 10:17:12,893 INFO    MainThread:109749 [wandb_init.py:init():591] re-initializing run, found existing run on stack: Top 5 Airline Pie Chart
2024-03-22 10:17:12,897 INFO    MainThread:109749 [wandb_run.py:_finish():1970] finishing run ghsouvikprof/Flight Fare/Top 5 Airline Pie Chart
2024-03-22 10:17:12,900 ERROR   MainThread:109749 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-03-22 10:17:12,901 INFO    MainThread:109749 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-22 10:17:12,901 INFO    MainThread:109749 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-22 10:17:12,901 INFO    MainThread:109749 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-22 10:17:12,903 INFO    MainThread:109749 [wandb_run.py:_restore():2193] restore
2024-03-22 10:17:12,904 INFO    MainThread:109749 [wandb_run.py:_restore():2199] restore done
2024-03-22 10:18:12,759 INFO    MainThread:109749 [wandb_init.py:init():616] starting backend
2024-03-22 10:18:12,759 INFO    MainThread:109749 [wandb_init.py:init():620] setting up manager
2024-03-22 10:18:12,767 INFO    MainThread:109749 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-22 10:18:12,773 INFO    MainThread:109749 [wandb_init.py:init():628] backend started and connected
2024-03-22 10:18:12,876 INFO    MainThread:109749 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-22 10:18:12,876 INFO    MainThread:109749 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-22 10:18:12,876 INFO    MainThread:109749 [wandb_init.py:init():720] updated telemetry
2024-03-22 10:18:12,941 INFO    MainThread:109749 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
