2024-03-22 10:00:47,589 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-22 10:00:47,590 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Configure stats pid to 109749
2024-03-22 10:00:47,590 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Loading settings from /home/souvik/.config/wandb/settings
2024-03-22 10:00:47,591 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Loading settings from /mnt/d/WSL/Flight-Fare-Prediction/wandb/settings
2024-03-22 10:00:47,591 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-22 10:00:47,591 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-22 10:00:47,592 INFO    MainThread:109749 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240322_100047-Info/logs/debug.log
2024-03-22 10:00:47,593 INFO    MainThread:109749 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240322_100047-Info/logs/debug-internal.log
2024-03-22 10:00:47,593 INFO    MainThread:109749 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd23745a350>
2024-03-22 10:00:47,594 INFO    MainThread:109749 [wandb_init.py:init():566] calling init triggers
2024-03-22 10:00:47,594 INFO    MainThread:109749 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-22 10:00:47,595 INFO    MainThread:109749 [wandb_init.py:init():591] re-initializing run, found existing run on stack: Info
2024-03-22 10:00:47,605 INFO    MainThread:109749 [wandb_run.py:_finish():1970] finishing run ghsouvikprof/Flight Fare Prediction/Info
2024-03-22 10:00:47,606 INFO    MainThread:109749 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-22 10:00:47,607 INFO    MainThread:109749 [wandb_run.py:_restore():2193] restore
2024-03-22 10:00:47,608 INFO    MainThread:109749 [wandb_run.py:_restore():2199] restore done
2024-03-22 10:00:54,114 INFO    MainThread:109749 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-22 10:00:54,115 INFO    MainThread:109749 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-22 10:00:54,131 INFO    MainThread:109749 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-22 10:00:55,301 INFO    MainThread:109749 [wandb_init.py:init():616] starting backend
2024-03-22 10:00:55,301 INFO    MainThread:109749 [wandb_init.py:init():620] setting up manager
2024-03-22 10:00:55,307 INFO    MainThread:109749 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-22 10:00:55,312 INFO    MainThread:109749 [wandb_init.py:init():628] backend started and connected
2024-03-22 10:00:55,386 INFO    MainThread:109749 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-22 10:00:55,388 INFO    MainThread:109749 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-22 10:00:55,388 INFO    MainThread:109749 [wandb_init.py:init():720] updated telemetry
2024-03-22 10:00:55,443 INFO    MainThread:109749 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-22 10:00:57,803 INFO    MainThread:109749 [wandb_run.py:_on_init():2262] communicating current version
2024-03-22 10:00:58,719 INFO    MainThread:109749 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.16.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-03-22 10:00:58,720 INFO    MainThread:109749 [wandb_init.py:init():804] starting run threads in backend
2024-03-22 10:01:05,156 INFO    MainThread:109749 [wandb_run.py:_console_start():2241] atexit reg
2024-03-22 10:01:05,158 INFO    MainThread:109749 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-22 10:01:05,158 INFO    MainThread:109749 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-22 10:01:05,159 INFO    MainThread:109749 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-22 10:01:05,161 INFO    MainThread:109749 [wandb_init.py:init():847] run started, returning control to user process
2024-03-22 10:01:05,256 INFO    MainThread:109749 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-22 10:01:05,256 INFO    MainThread:109749 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-22 10:01:38,091 INFO    MainThread:109749 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-22 10:01:38,118 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-22 10:01:38,118 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Configure stats pid to 109749
2024-03-22 10:01:38,119 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Loading settings from /home/souvik/.config/wandb/settings
2024-03-22 10:01:38,119 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Loading settings from /mnt/d/WSL/Flight-Fare-Prediction/wandb/settings
2024-03-22 10:01:38,119 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-22 10:01:38,120 INFO    MainThread:109749 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-22 10:01:38,120 INFO    MainThread:109749 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240322_100138-dataset/logs/debug.log
2024-03-22 10:01:38,121 INFO    MainThread:109749 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/d/WSL/Flight-Fare-Prediction/wandb/run-20240322_100138-dataset/logs/debug-internal.log
2024-03-22 10:01:38,121 INFO    MainThread:109749 [wandb_init.py:init():566] calling init triggers
2024-03-22 10:01:38,121 INFO    MainThread:109749 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-22 10:01:38,122 INFO    MainThread:109749 [wandb_init.py:init():591] re-initializing run, found existing run on stack: Info
2024-03-22 10:01:38,124 INFO    MainThread:109749 [wandb_run.py:_finish():1970] finishing run ghsouvikprof/Flight Fare/Info
2024-03-22 10:01:38,125 ERROR   MainThread:109749 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-03-22 10:01:38,125 INFO    MainThread:109749 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-22 10:01:38,126 INFO    MainThread:109749 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-22 10:01:38,126 INFO    MainThread:109749 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-22 10:01:38,127 INFO    MainThread:109749 [wandb_run.py:_restore():2193] restore
2024-03-22 10:01:38,127 INFO    MainThread:109749 [wandb_run.py:_restore():2199] restore done
2024-03-22 10:01:45,534 INFO    MainThread:109749 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-22 10:01:45,535 INFO    MainThread:109749 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-22 10:01:45,541 INFO    MainThread:109749 [wandb_run.py:_footer_sync_info():3825] logging synced files
